theme: jekyll-theme-minimal
title: Recrutement - Shoot Shoot 
description: Session de live coding pour le recrutement de Shoot Shoot
logo: assets/logo.svg
github: 
  is_project_page: false
  is_user_page: false
  
